version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa_server
    command: ["run", "--server", "--addr=0.0.0.0:8181", "/policies/policy.rego"]
    volumes:
      - ./opa:/policies
    ports:
      - "8181:8181"

volumes:
  postgres_data:
